{% set data = load_setup_py_data() %}

package:
  name: openalea.weberpenn
  version: {{ data.get('version') }}

source:
  path: ..

build:
  preserve_egg_dir: True
  number: 0
  script: python setup.py install

requirements:
  hold:
    - python {{PY_VER}}
    - setuptools
    - openalea.deploy

  run:
    - openalea.plantgl
    - openalea.mtg

test:
  imports:
    - openalea.weberpenn

about:
  home: http://github.com/openalea/weberpenn
  license: Cecill-C License
  summary: An extension of the Weber and Penn model.